server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: TeaMarket
  datasource:
    driver-class-name: org.postgresql.Driver